#!/usr/bin/env bash
#
# Download every xStock asset and its proof of reserves, then store one merged
# JSON file.
#
# Two public endpoints are used:
#   1. /public/assets          - catalog: name, symbol, logo, chains
#   2. /public/proof-of-reserves - sharesHeld and circulatingSupply per symbol
#
# Both endpoints are paginated with 100 items per page and a hasNextPage flag.
# This script walks the pages until the flag is false or a page returns nothing.
# The proof-of-reserves totalNodes value is wrong (830), so the loop uses the
# flag and the real count.
#
# Output: data/xstocks-assets.json
#   array of { name, symbol, sharesHeld, circulatingSupply }
# Output: data/xstocks-assets.js
#   the same data in a classic script, for the page to read
#
# Requires: curl, jq

set -euo pipefail

api_base="https://api.backed.fi/api/v2/public"
assets_url="$api_base/assets"
reserves_url="$api_base/proof-of-reserves"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(dirname "$script_dir")"
out_file="$repo_root/data/xstocks-assets.json"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

# fetch_pages <url> <prefix>
# Downloads every page and stores each raw page as <prefix>-<n>.json.
fetch_pages() {
    local url="$1"
    local prefix="$2"
    local page=1

    while true; do
        local body
        body="$(curl -sS "$url?page=$page")"

        if ! printf '%s' "$body" | jq -e '.nodes | type == "array"' >/dev/null 2>&1; then
            echo "Error: $prefix page $page did not return a valid list." >&2
            exit 1
        fi

        local count
        count="$(printf '%s' "$body" | jq '.nodes | length')"
        if [ "$count" -eq 0 ]; then
            break
        fi

        printf '%s' "$body" > "$tmp_dir/$prefix-$page.json"

        local has_next
        has_next="$(printf '%s' "$body" | jq -r '.page.hasNextPage // false')"
        echo "  $prefix page $page: $count items (hasNextPage=$has_next)"

        if [ "$has_next" != "true" ]; then
            break
        fi

        page=$((page + 1))
    done
}

echo "Fetching assets..."
fetch_pages "$assets_url" "assets"

echo "Fetching proof of reserves..."
fetch_pages "$reserves_url" "reserves"

# Flatten the nodes from every page into two flat arrays.
jq -s '[.[].nodes[]]' "$tmp_dir"/assets-*.json > "$tmp_dir/assets.all.json"
jq -s '[.[].nodes[]]' "$tmp_dir"/reserves-*.json > "$tmp_dir/reserves.all.json"

# Merge by symbol. Assets without a reserve entry get null values.
mkdir -p "$repo_root/data"
jq -n \
    --slurpfile assets "$tmp_dir/assets.all.json" \
    --slurpfile reserves "$tmp_dir/reserves.all.json" '
    ($reserves[0]
     | map({ key: .symbol, value: { sharesHeld, circulatingSupply } })
     | from_entries) as $reserve_map
    | $assets[0]
    | map(
        . as $asset
        | ($reserve_map[$asset.symbol] // { sharesHeld: null, circulatingSupply: null }) as $reserve
        | {
            name: $asset.name,
            symbol: $asset.symbol,
            sharesHeld: $reserve.sharesHeld,
            circulatingSupply: $reserve.circulatingSupply
          }
      )
    | map(select(.sharesHeld != "0"))
  ' > "$out_file"

# The page has no build step and no server. A classic script reads the snapshot
# from a global, so the page also works when the user opens index.html directly.
# Generate that wrapper from the JSON. Keep the JSON as the source of truth.
js_file="$repo_root/data/xstocks-assets.js"
{
    printf '// Generated by scripts/fetch-assets.sh. Do not edit this file.\n'
    printf '// The source of truth is data/xstocks-assets.json.\n'
    printf 'window.XSTOCKS_ASSETS = '
    cat "$out_file"
    printf ';\n'
} > "$js_file"

fetched_total="$(jq 'length' "$tmp_dir/assets.all.json")"
total="$(jq 'length' "$out_file")"
with_reserves="$(jq '[.[] | select(.circulatingSupply != null)] | length' "$out_file")"
missing="$(jq -r '[.[] | select(.circulatingSupply == null) | .symbol] | join(", ")' "$out_file")"
dropped=$((fetched_total - total))

echo "Wrote $total assets ($with_reserves with reserves) to $out_file"
echo "Wrote the browser wrapper to $js_file"
echo "Filtered out $dropped assets with zero shares held (fetched $fetched_total)"

if [ -n "$missing" ]; then
    echo "Assets without reserves: $missing"
fi
